## YAML Template.
services:
    
    database:
      container_name: "database"
      image: "bitnami/postgresql:latest"
      environment:
        TZ: "America/Sao_Paulo"
        PGTZ: "America/Sao_Paulo"
        POSTGRESQL_USERNAME: admin
        POSTGRESQL_PASSWORD: A7rT9wLz2k
        POSTGRESQL_DATABASE: database
        POSTGRESQL_PORT_NUMBER: 5442
      ports:
        - "0.0.0.0:5442:5442"
      volumes:
        - ./postgresql/data:/var/lib/postgresql/data
        
